site_name: 央央's Notebook
site_url: https://melody12020831.github.io/Notebook/
repo_name: Melody
repo_url: https://github.com/Melody12020831/Notebook/
site_description: 央央的笔记本
copyright: Copyright &copy; 2024 <a href="https://github.com/Melody12020831" target="_blank" rel="noopener">Melody</a>

theme: 
  name: 'material'
  language: 'zh'
  icon: 
    logo: material/notebook-outline
  custom_dir: overrides
  features:
    - content.code.copy
    - content.code.annotate
    - navigation.tracking
    - navigation.tabs
    - navigation.indexes
    - navigation.top
    - navigation.path
    - toc.follow
    - search.suggest
    - search.highlight
  font:
    text: LXGW WenKai Screen GB Screen
    code: JetBrains Mono
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: deep purple
      accent: light blue
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: deep purple
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode

  favicon: assets/images/icon.jpg

  
markdown_extensions:
  - toc:
      permalink: true
      toc_depth: 4
  # - meta
  - def_list
  - attr_list
  - md_in_html
  - sane_lists
  - admonition
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.snippets
  - pymdownx.magiclink
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg 
  - pymdownx.tabbed:
      alternate_style: true 
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.arithmatex:
      generic: true

validation:
  nav:
    omitted_files: info
    not_found: warn
    absolute_links: info
  links:
    not_found: ignore
    absolute_links: ignore
    unrecognized_links: ignore

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Melody12020831/
  analytics:
    provider: google
    property: G-002T22X4FB

extra_css:
    - https://gcore.jsdelivr.net/npm/katex@0.16.11/dist/katex.min.css
    - https://gcore.jsdelivr.net/npm/lxgw-wenkai-screen-webfont@1.1.0/style.css
    - https://gcore.jsdelivr.net/npm/lxgw-wenkai-webfont@1.1.0/style.css
    - css/custom.css
    - css/card.css
    - css/tasklist.css
    - css/flink.css
    - css/more_changelog.css
    - css/neoteroi-mkdocs.css
    - css/fold_toc.css
    - css/sidebar.css

extra_javascript:
    # - https://polyfill.io/v3/polyfill.min.js?features=es6
    - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml.js
    - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
    - https://gcore.jsdelivr.net/npm/katex@0.16.11/dist/katex.min.js
    - https://cdn.jsdelivr.net/npm/katex@0.16.11/dist/contrib/auto-render.min.js
    # - css/Javascripts/mathjax.js
    # - css/Javascripts/katex.js
    # Table Sort
    - https://unpkg.com/tablesort@5.3.0/dist/tablesort.min.js
    - css/javascripts/tablesort.js


plugins:
  # - rss
  - search:
      lang:
        - zh
        - en
      separator: '[\s\-\.]+'
  - glightbox
  #     width: 80%
  # - changelog
  # - heti
  # - tikzautomata
  - git-revision-date-localized:
      enable_creation_date: true
      type: datetime
      timezone: Asia/Shanghai
      exclude:
        - index.md
  - statistics:
      words_per_minute: 200
  # - mkdocs-jupyter:
  #     execute: false

nav:
  - Home: 
    - index.md
  - Computer Science:
    - Computer_Science/index.md
    - "ADS":
      - Computer_Science/ADS/index.md
      - Computer_Science/ADS/Homework.md
      - Computer_Science/ADS/organisedproblems.md
    - "CO":
      - Computer_Science/CO/index.md
      - Computer_Science/CO/Chapter 1.md
      - Computer_Science/CO/Chapter 2.md
      - Computer_Science/CO/Chapter 3.md
      - Computer_Science/CO/Chapter 4.md
      - Computer_Science/CO/Chapter 5.md
      - Computer_Science/CO/Chapter 6.md
      - Computer_Science/CO/COhomework.md
      - Computer_Science/CO/PPT_download.md
    - "DB":
      - Computer_Science/DB/index.md
      - Computer_Science/DB/Chapter1.md
      - Computer_Science/DB/Chapter2.md
      - Computer_Science/DB/Chapter3.md
      - Computer_Science/DB/Chapter4.md
      - Computer_Science/DB/Chapter5.md
      - Computer_Science/DB/Chapter6.md
      - Computer_Science/DB/Chapter7.md
      - Computer_Science/DB/Chapter8.md
      - Computer_Science/DB/Chapter12.md
      - Computer_Science/DB/Chapter13.md
      - Computer_Science/DB/Chapter14.md
      - Computer_Science/DB/Chapter15.md
      - Computer_Science/DB/Chapter16.md
      - Computer_Science/DB/Chapter17.md
      - Computer_Science/DB/Chapter18.md
      - Computer_Science/DB/Chapter19.md
      - Computer_Science/DB/homework.md
      - Computer_Science/DB/sql.md
    - "OOP":
      - Computer_Science/OOP/index.md
      - Computer_Science/OOP/Chapter1.md
      - Computer_Science/OOP/Chapter2.md
      - Computer_Science/OOP/Chapter3.md
      - Computer_Science/OOP/Chapter4.md
      - Computer_Science/OOP/Chapter5.md
      - Computer_Science/OOP/Chapter6.md
      - Computer_Science/OOP/Chapter7.md
      - Computer_Science/OOP/Chapter8.md
      - Computer_Science/OOP/Chapter9.md
      - Computer_Science/OOP/Chapter10.md
      - Computer_Science/OOP/Chapter11.md
      - Computer_Science/OOP/Chapter12.md
      - Computer_Science/OOP/Chapter13.md
      - Computer_Science/OOP/Chapter14.md
      - Computer_Science/OOP/Chapter15.md
      - Computer_Science/OOP/homework.md
      - Computer_Science/OOP/test_from_wk.md
      - Computer_Science/OOP/105_STL_Algorithmsin_Less_Than_an_Hour.md
    - "CA":
      - Computer_Science/CA/index.md
      - Computer_Science/CA/Chapter1.md
      - Computer_Science/CA/Chapter2.md
      - Computer_Science/CA/homework.md
      - Computer_Science/CA/CA_review.md
    - "TOC":
      - Computer_Science/TOC/index.md
      - Computer_Science/TOC/Chapter1.md
      - Computer_Science/TOC/Chapter2.md
      - Computer_Science/TOC/Chapter3.md
      - Computer_Science/TOC/Chapter4.md
      - Computer_Science/TOC/Chapter5.md
    - "OS":
      - Computer_Science/OS/index.md
      - Computer_Science/OS/Chapter1.md
      - Computer_Science/OS/Chapter2.md
      - Computer_Science/OS/Chapter3.md
      - Computer_Science/OS/Chapter4.md
      - Computer_Science/OS/Chapter5.md
      - Computer_Science/OS/Chapter6.md
      - Computer_Science/OS/Chapter7.md
      - Computer_Science/OS/Chapter8.md
      - Computer_Science/OS/Chapter9.md
      - Computer_Science/OS/Chapter10.md
      - Computer_Science/OS/Chapter11.md
      - Computer_Science/OS/Chapter12.md
      - Computer_Science/OS/Chapter13.md
    - "CN":
      - Computer_Science/CN/index.md
      - Computer_Science/CN/Chapter1.md
      - Computer_Science/CN/Chapter2.md
      - Computer_Science/CN/Chapter3.md
      - Computer_Science/CN/Chapter4.md
      - Computer_Science/CN/Chapter5.md
      - Computer_Science/CN/Chapter6.md
      - Computer_Science/CN/Chapter7.md
      - Computer_Science/CN/quiz.md
    - "CP":
      - Computer_Science/CP/index.md
      - Computer_Science/CP/Chapter1.md
      - Computer_Science/CP/Chapter2.md
      - Computer_Science/CP/Chapter3.md
      - Computer_Science/CP/Chapter4.md
      - Computer_Science/CP/Chapter5.md
      - Computer_Science/CP/Chapter6.md
      - Computer_Science/CP/Chapter7.md
      - Computer_Science/CP/Chapter8.md
      - Computer_Science/CP/Chapter9.md
      - Computer_Science/CP/Chapter10.md
      - Computer_Science/CP/Chapter11.md
      - Computer_Science/CP/Chapter13.md
      - Computer_Science/CP/Chapter14.md
      - Computer_Science/CP/Chapter18.md
      - "Homework":
          - Computer_Science/CP/HW/HW1.md
          - Computer_Science/CP/HW/HW2.md
          - Computer_Science/CP/HW/HW3.md
          - Computer_Science/CP/HW/HW4.md
          - Computer_Science/CP/HW/HW5.md
          - Computer_Science/CP/HW/HW6.md
          - Computer_Science/CP/HW/HW7.md
          - Computer_Science/CP/HW/HW8.md
          - Computer_Science/CP/HW/HW9.md
          - Computer_Science/CP/HW/HW10.md
          - Computer_Science/CP/HW/HW11.md
          - Computer_Science/CP/HW/HW13.md
    - "SE":
      - Computer_Science/SE/index.md
      - Computer_Science/SE/Chapter1.md
      - Computer_Science/SE/Chapter2.md
      - Computer_Science/SE/Chapter3.md
      - Computer_Science/SE/Chapter4.md
      - Computer_Science/SE/Chapter6.md
      - Computer_Science/SE/Chapter7.md
      - Computer_Science/SE/Chapter8.md
      - Computer_Science/SE/Chapter9.md
      - Computer_Science/SE/Chapter10.md
      - Computer_Science/SE/Chapter11.md
      - Computer_Science/SE/Chapter12.md
      - Computer_Science/SE/Chapter13.md
      - Computer_Science/SE/Chapter14.md
      - Computer_Science/SE/Chapter15.md
      - Computer_Science/SE/Chapter16.md
      - Computer_Science/SE/Chapter17.md
      - Computer_Science/SE/Chapter18.md
      - Computer_Science/SE/Chapter20.md
      - Computer_Science/SE/Chapter21.md
      - Computer_Science/SE/Chapter22.md
      - Computer_Science/SE/Chapter23.md
      - Computer_Science/SE/Chapter24.md
      - Computer_Science/SE/Chapter25.md
      - Computer_Science/SE/Chapter26.md
      - Computer_Science/SE/Chapter27.md
      - Computer_Science/SE/Chapter28.md
      - Computer_Science/SE/Chapter29.md
      - Computer_Science/SE/Chapter30.md
      - Computer_Science/SE/Chapter31.md
      - Computer_Science/SE/Chapter32.md
      - Computer_Science/SE/Chapter33.md
      - Computer_Science/SE/Chapter34.md
      - Computer_Science/SE/Chapter35.md
      - Computer_Science/SE/Chapter36.md
      - Computer_Science/SE/敏捷开发2.0.md
      - Computer_Science/SE/大模型驱动需求与设计.md
      - Computer_Science/SE/大模型驱动编码与评审.md
      - Computer_Science/SE/大模型赋能测试.md
      - Computer_Science/SE/大模型驱动运维与管理.md
      - "notes":
        - "SE00intro 课程介绍": Computer_Science/SE/notes/SE00intro 课程介绍.html
        - "SE00intro 课程介绍_test": Computer_Science/SE/notes/SE00intro 课程介绍_test.html
        - "SE01 软件的本质": Computer_Science/SE/notes/SE01 软件的本质.html
        - "SE01 软件的本质_test": Computer_Science/SE/notes/SE01 软件的本质_test.html
        - "SE02 软件工程": Computer_Science/SE/notes/SE02 软件工程.html
        - "SE02 软件工程_test": Computer_Science/SE/notes/SE02 软件工程_test.html
        - "SE03 软件过程结构": Computer_Science/SE/notes/SE03 软件过程结构.html
        - "SE03 软件过程结构_test": Computer_Science/SE/notes/SE03 软件过程结构_test.html
        - "SE04 过程模型": Computer_Science/SE/notes/SE04 过程模型.html
        - "SE04 过程模型_test": Computer_Science/SE/notes/SE04 过程模型_test.html
        - "SE06 软件工程中的人": Computer_Science/SE/notes/SE06 软件工程中的人.html
        - "SE06 软件工程中的人_test": Computer_Science/SE/notes/SE06 软件工程中的人_test.html
        - "SE07 指导实践的原则": Computer_Science/SE/notes/SE07 指导实践的原则.html
        - "SE07 指导实践的原则_test": Computer_Science/SE/notes/SE07 指导实践的原则_test.html
        - "SE08 理解需求": Computer_Science/SE/notes/SE08 理解需求.html
        - "SE08 理解需求_test": Computer_Science/SE/notes/SE08 理解需求_test.html
        - "SE09 基于场景的需求建模": Computer_Science/SE/notes/SE09 基于场景的需求建模.html
        - "SE09 基于场景的需求建模_test": Computer_Science/SE/notes/SE09 基于场景的需求建模_test.html
        - "SE10 基于类的需求建模": Computer_Science/SE/notes/SE10 基于类的需求建模.html
        - "SE10 基于类的需求建模_test": Computer_Science/SE/notes/SE10 基于类的需求建模_test.html
        - "SE11 行为建模": Computer_Science/SE/notes/SE11 行为建模.html
        - "SE11 行为建模_test": Computer_Science/SE/notes/SE11 行为建模_test.html
        - "SE12 设计概念": Computer_Science/SE/notes/SE12 设计概念.html
        - "SE12 设计概念_test": Computer_Science/SE/notes/SE12 设计概念_test.html
        - "SE13 架构设计": Computer_Science/SE/notes/SE13 架构设计.html
        - "SE13 架构设计_test": Computer_Science/SE/notes/SE13 架构设计_test.html
        - "SE14 构件级设计": Computer_Science/SE/notes/SE14 构件级设计.html
        - "SE14 构件级设计_test": Computer_Science/SE/notes/SE14 构件级设计_test.html
        - "SE15 用户界面设计": Computer_Science/SE/notes/SE15 用户界面设计.html
        - "SE15 用户界面设计_test": Computer_Science/SE/notes/SE15 用户界面设计_test.html
        - "SE16 基于模式的设计": Computer_Science/SE/notes/SE16 基于模式的设计.html
        - "SE16 基于模式的设计_test": Computer_Science/SE/notes/SE16 基于模式的设计_test.html
        - "SE17 Web应用设计": Computer_Science/SE/notes/SE17 Web应用设计.html
        - "SE17 Web应用设计_test": Computer_Science/SE/notes/SE17 Web应用设计_test.html
        - "SE18 移动应用设计": Computer_Science/SE/notes/SE18 移动应用设计.html
        - "SE18 移动应用设计_test": Computer_Science/SE/notes/SE18 移动应用设计_test.html
        - "SE20 评审技术": Computer_Science/SE/notes/SE20 评审技术.html
        - "SE20 评审技术_test": Computer_Science/SE/notes/SE20 评审技术_test.html
        - "SE21 软件质量保证": Computer_Science/SE/notes/SE21 软件质量保证.html
        - "SE21 软件质量保证_test": Computer_Science/SE/notes/SE21 软件质量保证_test.html
        - "SE22 软件测试策略": Computer_Science/SE/notes/SE22 软件测试策略.html
        - "SE22 软件测试策略_test": Computer_Science/SE/notes/SE22 软件测试策略_test.html
        - "SE23 测试传统应用": Computer_Science/SE/notes/SE23 测试传统应用.html
        - "SE23 测试传统应用_test": Computer_Science/SE/notes/SE23 测试传统应用_test.html
        - "SE24 测试面向对象应用": Computer_Science/SE/notes/SE24 测试面向对象应用.html
        - "SE24 测试面向对象应用_test": Computer_Science/SE/notes/SE24 测试面向对象应用_test.html
        - "SE25 Web应用测试": Computer_Science/SE/notes/SE25 Web应用测试.html
        - "SE25 Web应用测试_test": Computer_Science/SE/notes/SE25 Web应用测试_test.html
        - "SE26 移动应用测试": Computer_Science/SE/notes/SE26 移动应用测试.html
        - "SE26 移动应用测试_test": Computer_Science/SE/notes/SE26 移动应用测试_test.html
        - "SE27 安全工程": Computer_Science/SE/notes/SE27 安全工程.html
        - "SE27 安全工程_test": Computer_Science/SE/notes/SE27 安全工程_test.html
        - "SE28 形式化方法": Computer_Science/SE/notes/SE28 形式化方法.html
        - "SE28 形式化方法_test": Computer_Science/SE/notes/SE28 形式化方法_test.html
        - "SE29 软件配置管理": Computer_Science/SE/notes/SE29 软件配置管理.html
        - "SE29 软件配置管理_test": Computer_Science/SE/notes/SE29 软件配置管理_test.html
        - "SE30 产品度量": Computer_Science/SE/notes/SE30 产品度量.html
        - "SE30 产品度量_test": Computer_Science/SE/notes/SE30 产品度量_test.html
        - "SE31 项目管理概念": Computer_Science/SE/notes/SE31 项目管理概念.html
        - "SE31 项目管理概念_test": Computer_Science/SE/notes/SE31 项目管理概念_test.html
        - "SE32 项目过程度量": Computer_Science/SE/notes/SE32 项目过程度量.html
        - "SE32 项目过程度量_test": Computer_Science/SE/notes/SE32 项目过程度量_test.html
        - "SE33 估算": Computer_Science/SE/notes/SE33 估算.html
        - "SE33 估算_test": Computer_Science/SE/notes/SE33 估算_test.html
        - "SE34 项目调度": Computer_Science/SE/notes/SE34 项目调度.html
        - "SE34 项目调度_test": Computer_Science/SE/notes/SE34 项目调度_test.html
        - "SE35 风险分析": Computer_Science/SE/notes/SE35 风险分析.html
        - "SE35 风险分析_test": Computer_Science/SE/notes/SE35 风险分析_test.html
        - "SE36 软件维护": Computer_Science/SE/notes/SE36 软件维护.html
        - "SE36 软件维护_test": Computer_Science/SE/notes/SE36 软件维护_test.html
        - "SE37 敏捷开发": Computer_Science/SE/notes/SE37 敏捷开发.html
        - "SE37 敏捷开发_test": Computer_Science/SE/notes/SE37 敏捷开发_test.html
        - "SE38 机器学习在软件工程中的应用": Computer_Science/SE/notes/SE38 机器学习在软件工程中的应用.html
        - "SE38 机器学习在软件工程中的应用_test": Computer_Science/SE/notes/SE38 机器学习在软件工程中的应用_test.html
        - "大模型驱动运维与管理": Computer_Science/SE/notes/大模型驱动运维与管理.html
        - "大模型驱动运维与管理_test": Computer_Science/SE/notes/大模型驱动运维与管理_test.html
        - "大模型驱动需求与设计": Computer_Science/SE/notes/大模型驱动需求与设计.html
        - "大模型驱动需求与设计_test": Computer_Science/SE/notes/大模型驱动需求与设计_test.html
        - "开源软件前沿技术": Computer_Science/SE/notes/开源软件前沿技术.html
        - "开源软件前沿技术_test": Computer_Science/SE/notes/开源软件前沿技术_test.html
        - "敏捷开发": Computer_Science/SE/notes/敏捷开发.html
        - "敏捷开发_test": Computer_Science/SE/notes/敏捷开发_test.html
    - "AI":
      - Computer_Science/AI/index.md
    - "Visualization":
      - Computer_Science/Visualization/note.md
    - "编程语言":
      - Computer_Science/Programming_Language/python/CS50P_python.md
      - Computer_Science/Programming_Language/python/python100days.md
    - "Tools":
      - Computer_Science/Tools/Git.md
      - Computer_Science/Tools/reveal-md.md
  - Math: 
    - Math/index.md
    - "概率论与数理统计":
        - Math/Probability_Theory_and_Mathematical_Statistics/index.md
        - Math/Probability_Theory_and_Mathematical_Statistics/Chapter1.md
        - Math/Probability_Theory_and_Mathematical_Statistics/Chapter2.md
        - Math/Probability_Theory_and_Mathematical_Statistics/Chapter3.md
        - Math/Probability_Theory_and_Mathematical_Statistics/Chapter4.md
        - Math/Probability_Theory_and_Mathematical_Statistics/Chapter5.md
        - Math/Probability_Theory_and_Mathematical_Statistics/Chapter6.md
        - Math/Probability_Theory_and_Mathematical_Statistics/Chapter7.md
        - Math/Probability_Theory_and_Mathematical_Statistics/Chapter8.md
        - Math/Probability_Theory_and_Mathematical_Statistics/PPT_download.md
        - "Homework":
          - Math/Probability_Theory_and_Mathematical_Statistics/HW/Homework_index.md
          - Math/Probability_Theory_and_Mathematical_Statistics/HW/HW1.md
          - Math/Probability_Theory_and_Mathematical_Statistics/HW/HW2.md
          - Math/Probability_Theory_and_Mathematical_Statistics/HW/HW3.md
          - Math/Probability_Theory_and_Mathematical_Statistics/HW/HW4.md
          - Math/Probability_Theory_and_Mathematical_Statistics/HW/HW5.md
          - Math/Probability_Theory_and_Mathematical_Statistics/HW/HW6.md
          - Math/Probability_Theory_and_Mathematical_Statistics/HW/HW7.md
          - Math/Probability_Theory_and_Mathematical_Statistics/HW/HW8.md
          - Math/Probability_Theory_and_Mathematical_Statistics/HW/HW9.md
          - Math/Probability_Theory_and_Mathematical_Statistics/HW/HW10.md
          - Math/Probability_Theory_and_Mathematical_Statistics/HW/HW11.md
          - Math/Probability_Theory_and_Mathematical_Statistics/HW/HW12.md
          - Math/Probability_Theory_and_Mathematical_Statistics/HW/HW13.md
          - Math/Probability_Theory_and_Mathematical_Statistics/HW/HW14.md
  - Misccelleanous:
    - Miscellaneous/index.md
    - Miscellaneous/prompt/prompt.md
    - Miscellaneous/mermaid.md
    - "UBC":
      - Miscellaneous/UBC/block chain DAY 1.md
      - Miscellaneous/UBC/block chain DAY 2.md
      - Miscellaneous/UBC/block chain DAY 3.md
      - Miscellaneous/UBC/block chain DAY 4.md
      - Miscellaneous/UBC/block chain DAY 5.md
      - Miscellaneous/UBC/block chain DAY 6.md
      - Miscellaneous/UBC/block chain DAY 7.md
      - Miscellaneous/UBC/block chain DAY 8.md
    - Miscellaneous/cs231n/cs231n_note.md